version: '3.8'

services:
  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile.test
    depends_on:
      - client
      - server
    environment:
      - BASE_URL=http://client:3000
    volumes:
      - ./e2e/test-results:/e2e/test-results

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: perntodo_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 